"""Build the crawlable HTML directory for the site's three content pillars."""
from __future__ import annotations

import argparse
import html
import json
import os
import tempfile
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from urllib.parse import urlsplit


ROOT = Path(__file__).resolve().parents[1]
BASE_URL = "https://jaketroubleshoots.com"
PAGE_SIZE = 100
MASTER_PATH = "content-directory.html"
DIRECTORY_NAME = "directory"
GENERATED_MARKER = "<!-- Generated by tools/build_content_directory.py. Do not edit. -->"


def _filesystem_path(path: Path) -> Path:
    """Return a Windows extended-length path when the checkout path requires it."""
    resolved = path.resolve()
    value = str(resolved)
    if os.name == "nt" and not value.startswith("\\\\?\\"):
        return Path("\\\\?\\" + value)
    return resolved


class DirectoryBuildError(ValueError):
    """Raised when source records cannot produce a safe public directory."""


@dataclass(frozen=True)
class Pillar:
    key: str
    name: str
    singular_name: str
    source_path: str
    url_prefix: str
    page_prefix: str


PILLARS = (
    Pillar(
        key="troubleshooting-guides",
        name="Troubleshooting Guides",
        singular_name="troubleshooting guide",
        source_path="data/guides.json",
        url_prefix="guides/",
        page_prefix="troubleshooting-guides",
    ),
    Pillar(
        key="preventive-maintenance",
        name="Preventive Maintenance Procedures",
        singular_name="preventive maintenance procedure",
        source_path="data/preventive-maintenance.json",
        url_prefix="preventive-maintenance/",
        page_prefix="preventive-maintenance",
    ),
    Pillar(
        key="biomed-basics",
        name="Biomed Basics Articles",
        singular_name="Biomed Basics article",
        source_path="data/biomed-basics.json",
        url_prefix="biomed-basics/",
        page_prefix="biomed-basics",
    ),
)


def _read_json(path: Path) -> object:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as error:
        raise DirectoryBuildError(f"Required catalog does not exist: {path}") from error
    except json.JSONDecodeError as error:
        raise DirectoryBuildError(f"Invalid JSON in {path}: {error}") from error


def _records_for_pillar(root: Path, pillar: Pillar) -> list[dict[str, object]]:
    source = root / pillar.source_path
    data = _read_json(source)
    if not isinstance(data, list):
        raise DirectoryBuildError(f"Catalog must contain a JSON list: {source}")

    if pillar.key != "troubleshooting-guides":
        if not all(isinstance(record, dict) for record in data):
            raise DirectoryBuildError(f"Catalog contains a non-object record: {source}")
        return data

    records: list[dict[str, object]] = []
    for item in data:
        if isinstance(item, dict):
            records.append(item)
            continue
        if not isinstance(item, str) or not item.strip():
            raise DirectoryBuildError(f"Guide manifest contains an invalid shard entry: {item!r}")
        shard_relative = PurePosixPath(item)
        if shard_relative.is_absolute() or ".." in shard_relative.parts:
            raise DirectoryBuildError(f"Unsafe guide shard path: {item}")
        shard = root.joinpath(*shard_relative.parts)
        shard_data = _read_json(shard)
        if not isinstance(shard_data, list) or not all(isinstance(record, dict) for record in shard_data):
            raise DirectoryBuildError(f"Guide shard must contain a list of objects: {shard}")
        records.extend(shard_data)
    return records


def _validated_entries(root: Path, pillar: Pillar) -> list[tuple[str, str]]:
    entries: list[tuple[str, str]] = []
    for number, record in enumerate(_records_for_pillar(root, pillar), start=1):
        title = record.get("title")
        url = record.get("url")
        if not isinstance(title, str) or not title.strip():
            raise DirectoryBuildError(f"{pillar.source_path} record {number} has no valid title")
        if not isinstance(url, str) or not url.strip():
            raise DirectoryBuildError(f"{pillar.source_path} record {number} has no valid URL")
        title = " ".join(title.split())
        url = url.strip()
        parsed = urlsplit(url)
        relative = PurePosixPath(parsed.path)
        if (
            parsed.scheme
            or parsed.netloc
            or parsed.query
            or parsed.fragment
            or "\\" in url
            or relative.is_absolute()
            or ".." in relative.parts
            or not url.startswith(pillar.url_prefix)
            or relative.suffix.lower() != ".html"
            or relative.as_posix() != url
        ):
            raise DirectoryBuildError(f"Unsafe or unexpected {pillar.name} URL: {url}")
        target = root.joinpath(*relative.parts)
        if not _filesystem_path(target).is_file():
            raise DirectoryBuildError(f"Published destination does not exist for {url}: {target}")
        entries.append((title, url))
    return sorted(entries, key=lambda entry: (entry[0].casefold(), entry[1]))


def load_content(root: Path = ROOT) -> dict[Pillar, list[tuple[str, str]]]:
    """Load, validate, and deduplicate the authoritative published records."""
    content: dict[Pillar, list[tuple[str, str]]] = {}
    seen: dict[str, str] = {}
    for pillar in PILLARS:
        entries = _validated_entries(root, pillar)
        for title, url in entries:
            if url in seen:
                raise DirectoryBuildError(
                    f"Duplicate published URL {url!r} in {pillar.name}; already used by {seen[url]!r}"
                )
            seen[url] = title
        content[pillar] = entries
    return content


def _page_path(pillar: Pillar, page_number: int) -> str:
    return f"{DIRECTORY_NAME}/{pillar.page_prefix}-{page_number:03d}.html"


def _shell(*, title: str, description: str, canonical_path: str, prefix: str, main: str) -> str:
    canonical = f"{BASE_URL}/{canonical_path}"
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{html.escape(title)}</title>
  <meta name="description" content="{html.escape(description, quote=True)}">
  <link rel="canonical" href="{html.escape(canonical, quote=True)}">
  <link rel="stylesheet" href="{prefix}style.css?v=20260920-2">
  <link rel="icon" type="image/x-icon" href="{prefix}images/favicon.ico">
  <script src="{prefix}social-links.js" defer></script>
</head>
<body>
{GENERATED_MARKER}
<a class="skip-link" href="#page-heading">Skip to content</a>
<header>
  <a href="{prefix}index.html" class="site-logo">
    <img src="{prefix}images/logo.png" alt="Jake Troubleshoots Logo" class="site-icon">
    <span class="logo-text">Jake Troubleshoots</span>
  </a>
  <nav class="site-primary-nav" aria-label="Primary navigation">
    <a href="{prefix}guides.html">Guides</a>
    <a href="{prefix}preventive-maintenance.html">PMs</a>
    <a href="{prefix}biomed-basics.html">Basics</a>
    <a href="{prefix}search.html">Search</a>
    <details class="site-nav-more">
      <summary>More</summary>
      <div class="site-nav-menu">
        <a href="{prefix}biomed-education-certifications.html">Education &amp; Certifications</a>
        <a href="{prefix}biomed-jobs.html">Biomed Jobs</a>
        <a href="{prefix}vendors.html">Vendors</a>
        <a href="{prefix}index.html#biomed-quiz">Biomed Quiz</a>
        <a href="{prefix}contact.html">About &amp; Contact</a>
      </div>
    </details>
  </nav>
</header>
{main}
<footer>
  <p>Contact: <a href="mailto:contact@jaketroubleshoots.com" style="color:#8fff00;">contact@jaketroubleshoots.com</a></p>
  <p><a href="{prefix}privacy-policy.html">Privacy Policy</a> &nbsp;|&nbsp; <a href="{prefix}terms-of-use.html">Terms of Use</a></p>
  <p>Guides intended for trained personnel only.</p>
  <p>© 2026 Jake Troubleshoots</p>
</footer>
</body>
</html>
"""


def _master_page(content: dict[Pillar, list[tuple[str, str]]], page_size: int) -> str:
    sections = []
    total = sum(len(entries) for entries in content.values())
    for pillar, entries in content.items():
        page_count = (len(entries) + page_size - 1) // page_size
        links = []
        for index in range(page_count):
            start = index * page_size + 1
            end = min((index + 1) * page_size, len(entries))
            links.append(
                f'        <li><a href="{_page_path(pillar, index + 1)}">'
                f'{html.escape(pillar.name)} {start}&ndash;{end}</a></li>'
            )
        sections.append(
            f'''    <section class="content-box" id="{pillar.key}">
      <h2>{html.escape(pillar.name)}</h2>
      <p>{len(entries):,} published {html.escape(pillar.name.lower())}.</p>
      <ul>
{chr(10).join(links)}
      </ul>
    </section>'''
        )
    main = f'''<section class="hero">
  <h1 id="page-heading" tabindex="-1">Content Directory</h1>
  <p>Static, crawlable links to all {total:,} published troubleshooting guides, preventive maintenance procedures, and Biomed Basics articles.</p>
</section>
<main>
{chr(10).join(sections)}
</main>'''
    return _shell(
        title="Content Directory | Jake Troubleshoots",
        description="Browse static HTML directories for every published Jake Troubleshoots guide, preventive maintenance procedure, and Biomed Basics article.",
        canonical_path=MASTER_PATH,
        prefix="",
        main=main,
    )


def _pagination(pillar: Pillar, page_number: int, page_count: int) -> str:
    links = [f'<a href="../{MASTER_PATH}#{pillar.key}">Directory home</a>']
    if page_number > 1:
        links.append(f'<a href="{pillar.page_prefix}-{page_number - 1:03d}.html" rel="prev">Previous</a>')
    for number in range(1, page_count + 1):
        current = ' aria-current="page"' if number == page_number else ""
        links.append(
            f'<a href="{pillar.page_prefix}-{number:03d}.html"{current}>'
            f'Page {number}</a>'
        )
    if page_number < page_count:
        links.append(f'<a href="{pillar.page_prefix}-{page_number + 1:03d}.html" rel="next">Next</a>')
    return '<nav class="browse-buttons" aria-label="Directory pages">' + "\n        ".join(links) + "</nav>"


def _listing_page(
    pillar: Pillar,
    entries: list[tuple[str, str]],
    page_number: int,
    page_count: int,
    page_size: int,
) -> str:
    start = (page_number - 1) * page_size
    page_entries = entries[start:start + page_size]
    listing = "\n".join(
        f'        <li><a href="../{html.escape(url, quote=True)}">{html.escape(title)}</a></li>'
        for title, url in page_entries
    )
    page_title = f"{pillar.name} Directory – Page {page_number} of {page_count} | Jake Troubleshoots"
    description = (
        f"Browse published {pillar.name.lower()}, page {page_number} of {page_count}, "
        "with direct static HTML links to each resource."
    )
    navigation = _pagination(pillar, page_number, page_count)
    main = f'''<section class="hero">
  <h1 id="page-heading" tabindex="-1">{html.escape(pillar.name)} Directory – Page {page_number} of {page_count}</h1>
  <p>Page {page_number} of {page_count}. Direct links to published {html.escape(pillar.name.lower())}.</p>
</section>
<main>
  <section class="content-box">
    <h2>{html.escape(pillar.name)}: {start + 1}&ndash;{start + len(page_entries)}</h2>
    <ul>
{listing}
    </ul>
    {navigation}
  </section>
</main>'''
    return _shell(
        title=page_title,
        description=description,
        canonical_path=_page_path(pillar, page_number),
        prefix="../",
        main=main,
    )


def build_outputs(root: Path = ROOT, page_size: int = PAGE_SIZE) -> dict[str, str]:
    """Return all expected generated paths and deterministic UTF-8 text."""
    if page_size < 1:
        raise DirectoryBuildError("Page size must be at least 1")
    content = load_content(root)
    outputs = {MASTER_PATH: _master_page(content, page_size)}
    for pillar, entries in content.items():
        page_count = (len(entries) + page_size - 1) // page_size
        for page_number in range(1, page_count + 1):
            outputs[_page_path(pillar, page_number)] = _listing_page(
                pillar, entries, page_number, page_count, page_size
            )
    return outputs


def _generated_files(root: Path) -> set[str]:
    directory = root / DIRECTORY_NAME
    if not directory.exists():
        return set()
    found: set[str] = set()
    for path in directory.glob("*.html"):
        relative = path.relative_to(root).as_posix()
        text = path.read_text(encoding="utf-8")
        if GENERATED_MARKER not in text:
            raise DirectoryBuildError(
                f"Refusing to manage unmarked HTML file in generated directory: {relative}"
            )
        found.add(relative)
    return found


def changed_outputs(root: Path, outputs: dict[str, str]) -> tuple[list[str], list[str]]:
    """Return changed/missing expected paths and stale generated paths."""
    changed = []
    for relative, expected in outputs.items():
        path = root / relative
        if not path.is_file() or path.read_text(encoding="utf-8") != expected:
            changed.append(relative)
    stale = sorted(_generated_files(root) - set(outputs))
    return sorted(changed), stale


def write_outputs(root: Path, outputs: dict[str, str]) -> tuple[list[str], list[str]]:
    """Atomically write changed pages, then remove obsolete generated pages."""
    changed, stale = changed_outputs(root, outputs)
    for relative in changed:
        target = root / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        with tempfile.NamedTemporaryFile(
            mode="w", encoding="utf-8", newline="\n", dir=target.parent, delete=False
        ) as temporary:
            temporary.write(outputs[relative])
            temporary_path = Path(temporary.name)
        os.replace(temporary_path, target)
    for relative in stale:
        (root / relative).unlink()
    return changed, stale


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--page-size", type=int, default=PAGE_SIZE)
    parser.add_argument("--check", action="store_true", help="Validate and report drift without writing")
    args = parser.parse_args(argv)
    root = args.root.resolve()
    try:
        outputs = build_outputs(root, args.page_size)
        changed, stale = changed_outputs(root, outputs)
        if args.check:
            if changed or stale:
                print(f"Content directory is out of date: {len(changed)} changed/missing, {len(stale)} stale.")
                return 1
        else:
            changed, stale = write_outputs(root, outputs)
        content = load_content(root)
    except (DirectoryBuildError, OSError) as error:
        print(f"Content directory build failed: {error}")
        return 2
    total_links = sum(len(entries) for entries in content.values())
    action = "checked" if args.check else "generated"
    print(
        f"Content directory {action}: {total_links} destinations, {len(outputs) - 1} listing pages, "
        f"{len(changed)} changed/missing, {len(stale)} stale."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
